# ==========================================
#  Microservice Configuration: pago
# ==========================================

# Port Configuration
server.port=8089

# Spring Application Name
spring.application.name=ms-pago

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/bd_pagos?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true


# Springdoc OpenAPI Config
springdoc.api-docs.path=/api/pagos/v3/api-docs

