spring.application.name=ms_direccion

server.port=8086

spring.datasource.url=jdbc:mysql://localhost:3306/bd_direccion
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# URLs de los microservicios (usadas por Feign)
ms.usuario.url=http://localhost:8084
ms.estado.url=http://localhost:8083
