# ==========================================
#  Microservice Configuration: pago
# ==========================================

# Port Configuration
server.port=8089

# Spring Application Name
spring.application.name=pago

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/bd_pagos?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Feign Clients Config (Static Fallbacks)
ms.libro.url=http://localhost:8081
ms.categoria.url=http://localhost:8082
ms.estado.url=http://localhost:8083
ms.usuario.url=http://localhost:8084
ms.venta.url=http://localhost:8085
ms.direccion.url=http://localhost:8086
ms.resena.url=http://localhost:8087
ms.carrito.url=http://localhost:8088
ms.pago.url=http://localhost:8089
