server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Microservicio de Libros y Fotos
        - id: ms-estado
          uri: lb://ms-estado
          predicates:
            - Path=/api/estados/**

        - id: ms-categoria
          uri: lb://ms-categoria
          predicates:
            - Path=/api/categorias/**

        - id: ms-usuario
          uri: lb://ms-usuario
          predicates:
            - Path=/api/usuarios/**

        # ==========================================
        # 2. MICROSERVICIOS DE NEGOCIO / INTERMEDIOS
        # ==========================================
        - id: ms-libro
          uri: lb://ms-libro
          predicates:
            - Path=/api/libros/**,/api/fotos/**

        - id: ms-direccion
          uri: lb://ms-direccion
          predicates:
            - Path=/api/direcciones/**

        - id: ms-carrito
          uri: lb://ms-carrito
          predicates:
            - Path=/api/carrito/**

        # ==========================================
        # 3. MICROSERVICIOS TRANSACCIONALES / CIERRE
        # ==========================================
        - id: ms-venta
          uri: lb://ms-venta
          predicates:
            - Path=/api/ventas/**

        - id: ms-pago
          uri: lb://ms-pago
          predicates:
            - Path=/api/pagos/**

        - id: ms-envio
          uri: lb://ms-envio
          predicates:
            - Path=/api/envios/**

        - id: ms-resena
          uri: lb://ms-resena
          predicates:
            - Path=/api/resenas/**

eureka:
  client: 
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: api-gateway
    instance-id: api-gateway:${server.port}

logging:
  level:
    '[org.springframework.cloud.gateway]': DEBUG