# =============================================
#  MS-RESENA — application.properties
#  Base de datos: MySQL via XAMPP
# =============================================

server.port=8083

# --- MySQL (XAMPP) ---
spring.datasource.url=jdbc:mysql://localhost:3306/db_libreria?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# --- Nombre del microservicio ---
spring.application.name=ms-resena

# --- URLs de otros microservicios (Feign) ---
ms.libro.url=http://localhost:8081
ms.usuario.url=http://localhost:8082
