# ==========================================
#  Microservice Configuration: envio
# ==========================================

# Port Configuration
server.port=8090

# Spring Application Name
spring.application.name=ms-envio

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/bd_envios?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=rootpass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# JPA / Hibernate Configuration

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=ms-envio
eureka.instance.instance-id=ms-envio:${server.port}


# Springdoc OpenAPI Config
springdoc.api-docs.path=/api/envios/v3/api-docs

