spring.application.name=venta
server.port=8085

spring.datasource.url=jdbc:mysql://localhost:3306/bd_ventas
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#propiedad personalizada para las url de los microservicios que debo comunicarme
ms.estado.url=http://localhost:8083

ms.usuario.url=http://localhost:8084
