server:
  port: 8088

spring:
  application:
    name: carrito
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/bd_carritos}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Feign Clients Config
ms:
  usuario:
    url: ${MS_USUARIO_URL:http://localhost:8084}
  libro:
    url: ${MS_LIBRO_URL:http://localhost:8081}
